# Generated by Django 4.1.3 on 2022-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.FloatField(),
        ),
    ]
